project:
  type: website

website:
  title: "Just Another Statistics Textbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://github.com/Reading-Psych/jast/discussions/categories/possible-errors-in-the-document
        text: Report an error
      - href: https://github.com/Reading-Psych/jast/discussions/categories/requests-for-clarifications
        text: Request a clarification
      - href: https://github.com/Reading-Psych/jast/discussions/categories/suggest-content
        text: Suggest Content

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
          - about.qmd
          - installing.qmd
      - section: "Statistics Basics"
        contents:
          - statsBasics/statsBasics.qmd      
      - section: "R Basics"
        contents:
          - rBasics/filetypes.qmd
          - rBasics/fundamentals.qmd
      - section: "Describing Data"
        contents:
          - describingData/describingData.qmd
          - describingData/centralTendency.qmd
          - describingData/dispersion.qmd
          - describingData/distribution.qmd
      - section: "Transforming Data"
        contents: 
          - transformingData/transformingData.qmd
      - section: "Correlation"
        contents:
          - correlations/correlations.qmd
      - section: "Simple Regressions"
        contents:
          - simpleRegressions/simpleRegressions.qmd
      - section: "Multiple Regressions"
        contents:
          - multipleRegressions/multipleRegressions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



