project:
  type: website
  output-dir: docs

website:
  title: "Just Another Statistics Textbook"
  favicon: "logo/logo.jpeg"
  navbar:
    background: "#006599"
    logo: "logo/logo.jpeg"
    right:
      - href: https://github.com/Reading-Psych/jast/discussions/categories/possible-errors-in-the-document
        text: Report an error
      - href: https://github.com/Reading-Psych/jast/discussions/categories/requests-for-clarifications
        text: Request a clarification
      - href: https://github.com/Reading-Psych/jast/discussions/categories/suggest-content
        text: Suggest Content

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
          - installing.qmd
      - section: "Statistics Basics"
        contents:
          - statsBasics/statsBasics.qmd
          - statsBasics/eNumbers.qmd    
      - section: "R Basics"
        contents:
          - rBasics/filetypes.qmd
          - rBasics/fundamentals.qmd
          - rBasics/logic.qmd
      - section: "Describing Data"
        contents:
          - describingData/describingData.qmd
          - describingData/centralTendency.qmd
          - describingData/dispersion.qmd
      - section: "Distributions"
        contents:
          - distributions/normal.qmd
          - distributions/skewness.qmd
          - distributions/kurtosis.qmd
          - distributions/transforming.qmd
      - section: "Correlation"
        contents:
          - correlations/correlations.qmd
          - correlations/cooksd.qmd
      - section: "Regressions"
        contents:
          - regressions/simpleRegressions.qmd
          - regressions/multipleRegressions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



