---
editor: visual
---

```{=html}
<style>
#hide_show_button{
  position:fixed;
  right: 10px;
  bottom: 10px;
}
</style>
```
<button class="btn bi bi-arrows-angle-expand" id="hide_show_button" style="color: white; background-color:#006599">Show/Hide all</button>

::: {.callout-caution collapse="true"}
## Course Overview

```{r echo=FALSE}

page_colors = list(
  
  
  ancova_bg = "grey",                  ancova_text = "black",
  between_anova_bg = "orange",         between_anova_text = "black",
  binomial_bg = "grey",                binomial_text = "black",
  central_tendency_bg = "white",       central_tendency_text = "black",
  contingency_bg = "grey",             contingency_text = "black",
  correlations_bg = "grey",            correlations_text = "black",
  dispersion_bg = "white",              dispersion_text = "black",
  dummy_effect_bg = "grey",            dummy_effect_text = "black",
  fdr_bg = "grey",                     fdr_text = "black",
  fwer_bg = "grey",                    fwer_text = "black",
  fwer_vs_fdr_bg = "grey",             fwer_vs_fdr_text = "black",
  glm_bg = "grey",                     glm_text = "black",
  kurtosis_bg = "red",                  kurtosis_text = "black",
  mediation_bg = "red",                 mediation_text = "black",
  mixed_anova_bg = "orange",            mixed_anova_text = "black",
  multiple_regression_bg = "grey",     multiple_regression_text = "black",
  normal_bg = "grey",                  normal_text = "black",
  partial_correlations_bg = "grey",    partial_correlations_text = "black",
  permutation_bg = "grey",             permutation_text = "black",
  probability_bg = "grey",             probability_text = "black",
  rep_measures_anova_bg = "red",        rep_measures_anova_text = "black",
  simple_regression_bg = "grey",       simple_regression_text = "black",
  skewness_bg = "grey",                skewness_text = "black",
  stats_basics_bg = "white",            stats_basics_text = "black",
  transforming_bg = "grey",            transforming_text = "black",
  ttests_bg = "orange",                 ttests_text = "black"
  
)
if(exists("this_page")){
  page_colors[[paste(this_page,"_bg", sep="")]] = "blue"
  page_colors[[paste(this_page,"_text", sep="")]] = "white"
}



DiagrammeR::grViz(paste(
  '
  digraph "Course Overview" {
  rankdir=TB;
  fontname="Helvetica,Arial,sans-serif"
	node [fontname="Helvetica,Arial,sans-serif"]
	edge [fontname="Helvetica,Arial,sans-serif"]
	graph [ newrank = true, nodesep = 0.25, ranksep = .5, overlap = false, splines = curve,]
	node [ fixedsize = false, fillcolor = "white", fontsize = 24, height = 1, shape = box, style = "filled,setlinewidth(5)", width = 4]
	edge [arrowhead = none,arrowsize = 0.5,labelfontname = "Ubuntu",weight = 10,style = "filled,setlinewidth(5)"]
	
	subgraph system {
	  
		node [color = "#006688"]
		edge [color = "#006688"]
		
		ancova              [fillcolor="', page_colors[["ancova_bg"]] ,'",fontcolor="', page_colors[["ancova_text"]],'"label = "ANCOVA", URL = "../GeneralLinearModels/ancova.html"]
    between_anova       [fillcolor="', page_colors[["between_anova_bg"]] ,'",fontcolor="', page_colors[["between_anova_text"]],'"label = "One-way ANOVA", URL = "../GeneralLinearModels/oneWayAnova.html"]
		binomial            [fillcolor="', page_colors[["binomial_bg"]] ,'",fontcolor="', page_colors[["binomial_text"]],'"URL = "../distributions/binomial.html", label = "Binomial Distribution"]
		central_tendency    [fillcolor="', page_colors[["central_tendency_bg"]] ,'",fontcolor="', page_colors[["central_tendency_text"]],'"URL = "../describingData/centralTendency.html", fixedsize = true, label= "Central Tendency"]
		#cooksd[ label     = "Cooks D", URL       = "", fillcolor = red]
		contingency         [fillcolor="', page_colors[["contingency_bg"]] ,'",fontcolor="', page_colors[["contingency_text"]],'"URL = "../categorical/contingency.html", fixedsize = true, label = "Contingency"]
		correlations        [fillcolor="', page_colors[["correlations_bg"]] ,'",fontcolor="', page_colors[["correlations_text"]],'"URL = "../correlations/correlations.html", fixedsize = true, label= "Correlations"]
		dispersion          [fillcolor="', page_colors[["dispersion_bg"]] ,'",fontcolor="', page_colors[["dispersion_text"]],'"URL       = "../describingData/dispersion.html",label     = "Dispersion"]
		dummy_effect        [fillcolor="', page_colors[["dummy_effect_bg"]] ,'",fontcolor="', page_colors[["dummy_effect_text"]],'"URL       = "../describingData/dispersion.html",label     = "Dummy and Effect Coding"]
		fdr                 [fillcolor="', page_colors[["fdr_bg"]] ,'",fontcolor="', page_colors[["fdr_text"]],'"URL = "../multipleTesting/fdr.html",label = "False Discovery Rate"]
	  fwer                [fillcolor="', page_colors[["fwer_bg"]] ,'",fontcolor="', page_colors[["fwer_text"]],'"URL = "../multipleTesting/fwer.html",label = "Family-Wise Error Rate"]
    fwer_vs_fdr         [fillcolor="', page_colors[["fwer_vs_fdr_bg"]] ,'",fontcolor="', page_colors[["fwer_vs_fdr_text"]],'"label = "FWER vs. FDR",URL = "../multipleTesting/fwer_vs_fdr.html"]
    glm                 [fillcolor="', page_colors[["glm_bg"]] ,'",fontcolor="', page_colors[["glm_text"]],'"URL       = "../GeneralLinearModels/generalLinearModels.html",label     = "General Linear Models"]
    #kurtosis            [fillcolor="', page_colors[["kurtosis_bg"]] ,'",fontcolor="', page_colors[["kurtosis_text"]],'"URL       = "",label     = "Kurtosis",fillcolor = "red"]
    mediation           [fillcolor="', page_colors[["mediation_bg"]] ,'",fontcolor="', page_colors[["mediation_text"]],'"URL = "",fillcolor = "red",label = "Mediation"]
    mixed_anova         [fillcolor="', page_colors[["mixed_anova_bg"]] ,'",fontcolor="', page_colors[["mixed_anova_text"]],'"label = "Mixed ANOVA",URL = "../GeneralLinearModels/mixedAnova.html",]
		multiple_regression [fillcolor="', page_colors[["multiple_regression_bg"]] ,'",fontcolor="', page_colors[["multiple_regression_text"]],'"label     = "Multiple Regression",URL       = "../regressions/multipleRegressions.html"]
		normal              [fillcolor="', page_colors[["normal_bg"]] ,'",fontcolor="', page_colors[["normal_text"]],'"URL = "../distributions/normal.html", label= "Normal Distribution"]
		partial_correlations[fillcolor="', page_colors[["partial_correlations_bg"]] ,'",fontcolor="', page_colors[["partial_correlations_text"]],'"label ="Partial Correlations",URL = "../correlations/partialCorrelations.html",]
		permutation         [fillcolor="', page_colors[["permutation_bg"]] ,'",fontcolor="', page_colors[["permutation_text"]],'"label = "Permutations",URL = "../permutations/permutations.html",]
		probability         [fillcolor="', page_colors[["probability_bg"]] ,'",fontcolor="', page_colors[["probability_text"]],'"label = "Probability",URL = "../statsBasics/probability.html",fixedsize = true]
		rep_measures_anova  [fillcolor="', page_colors[["rep_measures_anova_bg"]] ,'",fontcolor="', page_colors[["rep_measures_anova_text"]],'"label = "Repeated Measures",URL = "../GeneralLinearModels/repeatedAnova.html",]
		simple_regression   [fillcolor="', page_colors[["simple_regression_bg"]] ,'",fontcolor="', page_colors[["simple_regression_text"]],'"label="Simple Regression", URL = "../regressions/simpleRegressions.html",]
		skewness            [fillcolor="', page_colors[["skewness_bg"]] ,'",fontcolor="', page_colors[["skewness_text"]],'"label = "Skewness", URL   = "../distributions/skewness.html"]
		stats_basics        [fillcolor="', page_colors[["stats_basics_bg"]] ,'",fontcolor="', page_colors[["stats_basics_text"]],'"label = "Statistics Basics",URL   = "../statsBasics/statsBasics.html"]
		transforming        [fillcolor="', page_colors[["transforming_bg"]] ,'",fontcolor="', page_colors[["transforming_text"]],'" label = "Transforming Data", URL = "../distributions/transforming.html"]
		ttests              [fillcolor="', page_colors[["ttests_bg"]] ,'",fontcolor="', page_colors[["ttests_text"]],'", label = "T-Tests", URL = "../GeneralLinearModels/TTests.html",]
	}
	/* connections */
	between_anova -> ancova
	binomial -> contingency
	binomial -> normal[
    #style = "dashed",
    #row = func
	]
	central_tendency -> dispersion
	#correlations -> cooksd
	correlations -> partial_correlations
	correlations -> simple_regression
	dispersion -> normal
	dummy_effect -> multiple_regression
	dummy_effect -> ttests
	fdr -> fwer_vs_fdr
	fwer -> fwer_vs_fdr
	glm -> ttests
  mixed_anova -> ancova
	multiple_regression -> mediation
	normal -> correlations
	normal -> contingency
	normal -> glm
	#normal -> kurtosis
	normal -> skewness[
    #style = "dashed",
    #row = func
	]
	probability -> contingency
	probability -> fwer
	probability -> fdr
	simple_regression -> multiple_regression
	simple_regression -> dummy_effect
	skewness -> transforming
	stats_basics -> central_tendency
	stats_basics -> probability
	# not invcluding the below because it makes the figure less readable
	#r_fundamentals -> central_tendency
	#r_fundamentals -> probability
	#excel_fundamentals -> central_tendency
	#excel_fundamentals -> probability
	transforming -> correlations
	ttests -> mixed_anova
	ttests -> between_anova
	ttests -> rep_measures_anova
	rep_measures_anova -> ancova
	
	
	
  # edge[ style = invis ];
  ancova -> permutation
  rep_measures_anova -> permutation
  between_anova -> permutation
  correlations -> permutation
  #mediation -> permutation  [
  #  style = "dashed",
    #row = func
	#] 
  #multiple_regression -> permutation  [
  #  style = "dashed",
  #  #row = func
	#] 
  #partial_correlations -> permutation
  #simple_regression -> permutation  [
  #  style = "dashed",
  #  #row = func
	#] 
  ttests -> permutation
}
  '
, sep=""))
```

[**Red**]{style="color:red"} means that the page does not exist yet

[**Gray**]{style="color:gray"} means that the page doesn't yet have separation of different levels of understanding

[**Orange**]{style="color:orange"} means that the page is started

In this website you can choose to expand or shrink the page to match the level of understanding you want.

-   If you do not expand any (green) subsections then you will only see the most superficial level of description about the statistics. If you expand the green subsections you will get details that are required to complete the tests, but perhaps not all the explanations for why the statistics work.

::: {.callout-tip appearance="minimal"}
## An example of a green subsection
:::

-   If you expand the blue subsections you will also see some explanations that will give you a more complete understanding. If you are completing MSc-level statistics you would be expected to understand all the blue subsections.

::: {.callout-note appearance="minimal"}
## An example of a blue subsection
:::

-   Red subsections will go deeper than what is expected at MSc level, such as testing higher level concepts.

::: {.callout-warning appearance="minimal"}
## An example of a red subsection
:::
:::

```{=html}
<script>
document.getElementById("hide_show_button").onclick = function(){
  //alert('hi');
  // select all elements with the data-bs-toggle attribute
  const elements = document.querySelectorAll('[data-bs-toggle]');

  // loop through the elements and toggle their collapsed state
  elements.forEach(element => {
    const isCollapsed = element.classList.contains('collapsed');
    //if (!isCollapsed) {
      element.click();
    //}
  });
}
</script>
```
