<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Just Another Statistics Textbook - Dispersion</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Just Another Statistics Textbook</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/Reading-Psych/jast/discussions/categories/possible-errors-in-the-document">Report an error</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/Reading-Psych/jast/discussions/categories/requests-for-clarifications">Request a clarification</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/Reading-Psych/jast/discussions/categories/suggest-content">Suggest Content</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Dispersion</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Welcome</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">About</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installing.html" class="sidebar-item-text sidebar-link">Installing R(Studio)</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Statistics Basics</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statsBasics/statsBasics.html" class="sidebar-item-text sidebar-link">Statistics Basics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statsBasics/eNumbers.html" class="sidebar-item-text sidebar-link">Scientific Notation</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">R Basics</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rBasics/filetypes.html" class="sidebar-item-text sidebar-link">Types of Scripts</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rBasics/fundamentals.html" class="sidebar-item-text sidebar-link">R Fundamentals</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Describing Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../describingData/describingData.html" class="sidebar-item-text sidebar-link">Describing Data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../describingData/centralTendency.html" class="sidebar-item-text sidebar-link">Central Tendency</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../describingData/dispersion.html" class="sidebar-item-text sidebar-link active">Dispersion</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Distributions</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../distributions/normal.html" class="sidebar-item-text sidebar-link">Normal Distribution (incomplete)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../distributions/skewness.html" class="sidebar-item-text sidebar-link">Skewness (incomplete)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../distributions/kurtosis.html" class="sidebar-item-text sidebar-link">Kurtosis (incomplete)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../distributions/transforming.html" class="sidebar-item-text sidebar-link">Transforming Data</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Correlation</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  correlations/correlations.qmd
  </li>
          <li class="sidebar-item">
  correlations/cooksd.qmd
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Regressions</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simpleRegressions/simpleRegressions.html" class="sidebar-item-text sidebar-link">Simple Regressions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../multipleRegressions/multipleRegressions.html" class="sidebar-item-text sidebar-link">Multiple Regressions</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#range" id="toc-range" class="nav-link active" data-scroll-target="#range">Range</a></li>
  <li><a href="#variance" id="toc-variance" class="nav-link" data-scroll-target="#variance">Variance</a>
  <ul class="collapse">
  <li><a href="#population-variance" id="toc-population-variance" class="nav-link" data-scroll-target="#population-variance">Population Variance</a></li>
  <li><a href="#sample-variance" id="toc-sample-variance" class="nav-link" data-scroll-target="#sample-variance">Sample variance</a></li>
  </ul></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of Freedom</a></li>
  <li><a href="#standard-deviation-sd" id="toc-standard-deviation-sd" class="nav-link" data-scroll-target="#standard-deviation-sd">Standard deviation (SD)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Dispersion</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>To understand distribution (later), it’s helpful to clarify some more basic concepts around how data is <strong>dispersed</strong> or spread.</p>
<section id="range" class="level2">
<h2 class="anchored" data-anchor-id="range">Range</h2>
<p><strong>Range</strong> simply captures the min and the maximum values. Lets look at the min and max for the life expectancy data from 2007:</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the gapminder data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new data frame that only focuses on data from 2007</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>gapminder_2007 <span class="ot">&lt;-</span> <span class="fu">subset</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  gapminder,   <span class="co"># the data set</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  year <span class="sc">==</span> <span class="dv">2007</span>     </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(gapminder_2007<span class="sc">$</span>lifeExp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.613</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(gapminder_2007<span class="sc">$</span>lifeExp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 82.603</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the markdownTable module </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> markdownTable <span class="im">import</span> markdownTable</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># load the gapminder module and import the gapminder dataset</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> gapminder <span class="im">import</span> gapminder</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new data frame that only focuses on data from 2007</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>gapminder_2007 <span class="op">=</span> gapminder.loc[gapminder[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2007</span>]</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>gapminder_2007[<span class="st">'lifeExp'</span>].<span class="bu">min</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>39.613</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>gapminder_2007[<span class="st">'lifeExp'</span>].<span class="bu">max</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>82.603</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>So the <strong>range</strong> for life expectancy in 2007 was between 39.613 and 82.603.</p>
</section>
<section id="variance" class="level2">
<h2 class="anchored" data-anchor-id="variance">Variance</h2>
<section id="population-variance" class="level3">
<h3 class="anchored" data-anchor-id="population-variance">Population Variance</h3>
<p><strong>Variance</strong> is how much the data varies around a mean. To capture this, we compare each individual’s score with the mean, so lets do this with our gapminder data’s life expectancy:</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_variance_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">life_expectancy =</span> gapminder_2007<span class="sc">$</span>lifeExp,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">diff_from_mean  =</span> gapminder_2007<span class="sc">$</span>lifeExp <span class="sc">-</span> <span class="fu">mean</span>(gapminder_2007<span class="sc">$</span>lifeExp)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>rmarkdown<span class="sc">::</span><span class="fu">paged_table</span>(life_expectancy_variance_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["life_expectancy"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["diff_from_mean"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"43.828","2":"-23.1794225"},{"1":"76.423","2":"9.4155775"},{"1":"72.301","2":"5.2935775"},{"1":"42.731","2":"-24.2764225"},{"1":"75.320","2":"8.3125775"},{"1":"81.235","2":"14.2275775"},{"1":"79.829","2":"12.8215775"},{"1":"75.635","2":"8.6275775"},{"1":"64.062","2":"-2.9454225"},{"1":"79.441","2":"12.4335775"},{"1":"56.728","2":"-10.2794225"},{"1":"65.554","2":"-1.4534225"},{"1":"74.852","2":"7.8445775"},{"1":"50.728","2":"-16.2794225"},{"1":"72.390","2":"5.3825775"},{"1":"73.005","2":"5.9975775"},{"1":"52.295","2":"-14.7124225"},{"1":"49.580","2":"-17.4274225"},{"1":"59.723","2":"-7.2844225"},{"1":"50.430","2":"-16.5774225"},{"1":"80.653","2":"13.6455775"},{"1":"44.741","2":"-22.2664225"},{"1":"50.651","2":"-16.3564225"},{"1":"78.553","2":"11.5455775"},{"1":"72.961","2":"5.9535775"},{"1":"72.889","2":"5.8815775"},{"1":"65.152","2":"-1.8554225"},{"1":"46.462","2":"-20.5454225"},{"1":"55.322","2":"-11.6854225"},{"1":"78.782","2":"11.7745775"},{"1":"48.328","2":"-18.6794225"},{"1":"75.748","2":"8.7405775"},{"1":"78.273","2":"11.2655775"},{"1":"76.486","2":"9.4785775"},{"1":"78.332","2":"11.3245775"},{"1":"54.791","2":"-12.2164225"},{"1":"72.235","2":"5.2275775"},{"1":"74.994","2":"7.9865775"},{"1":"71.338","2":"4.3305775"},{"1":"71.878","2":"4.8705775"},{"1":"51.579","2":"-15.4284225"},{"1":"58.040","2":"-8.9674225"},{"1":"52.947","2":"-14.0604225"},{"1":"79.313","2":"12.3055775"},{"1":"80.657","2":"13.6495775"},{"1":"56.735","2":"-10.2724225"},{"1":"59.448","2":"-7.5594225"},{"1":"79.406","2":"12.3985775"},{"1":"60.022","2":"-6.9854225"},{"1":"79.483","2":"12.4755775"},{"1":"70.259","2":"3.2515775"},{"1":"56.007","2":"-11.0004225"},{"1":"46.388","2":"-20.6194225"},{"1":"60.916","2":"-6.0914225"},{"1":"70.198","2":"3.1905775"},{"1":"82.208","2":"15.2005775"},{"1":"73.338","2":"6.3305775"},{"1":"81.757","2":"14.7495775"},{"1":"64.698","2":"-2.3094225"},{"1":"70.650","2":"3.6425775"},{"1":"70.964","2":"3.9565775"},{"1":"59.545","2":"-7.4624225"},{"1":"78.885","2":"11.8775775"},{"1":"80.745","2":"13.7375775"},{"1":"80.546","2":"13.5385775"},{"1":"72.567","2":"5.5595775"},{"1":"82.603","2":"15.5955775"},{"1":"72.535","2":"5.5275775"},{"1":"54.110","2":"-12.8974225"},{"1":"67.297","2":"0.2895775"},{"1":"78.623","2":"11.6155775"},{"1":"77.588","2":"10.5805775"},{"1":"71.993","2":"4.9855775"},{"1":"42.592","2":"-24.4154225"},{"1":"45.678","2":"-21.3294225"},{"1":"73.952","2":"6.9445775"},{"1":"59.443","2":"-7.5644225"},{"1":"48.303","2":"-18.7044225"},{"1":"74.241","2":"7.2335775"},{"1":"54.467","2":"-12.5404225"},{"1":"64.164","2":"-2.8434225"},{"1":"72.801","2":"5.7935775"},{"1":"76.195","2":"9.1875775"},{"1":"66.803","2":"-0.2044225"},{"1":"74.543","2":"7.5355775"},{"1":"71.164","2":"4.1565775"},{"1":"42.082","2":"-24.9254225"},{"1":"62.069","2":"-4.9384225"},{"1":"52.906","2":"-14.1014225"},{"1":"63.785","2":"-3.2224225"},{"1":"79.762","2":"12.7545775"},{"1":"80.204","2":"13.1965775"},{"1":"72.899","2":"5.8915775"},{"1":"56.867","2":"-10.1404225"},{"1":"46.859","2":"-20.1484225"},{"1":"80.196","2":"13.1885775"},{"1":"75.640","2":"8.6325775"},{"1":"65.483","2":"-1.5244225"},{"1":"75.537","2":"8.5295775"},{"1":"71.752","2":"4.7445775"},{"1":"71.421","2":"4.4135775"},{"1":"71.688","2":"4.6805775"},{"1":"75.563","2":"8.5555775"},{"1":"78.098","2":"11.0905775"},{"1":"78.746","2":"11.7385775"},{"1":"76.442","2":"9.4345775"},{"1":"72.476","2":"5.4685775"},{"1":"46.242","2":"-20.7654225"},{"1":"65.528","2":"-1.4794225"},{"1":"72.777","2":"5.7695775"},{"1":"63.062","2":"-3.9454225"},{"1":"74.002","2":"6.9945775"},{"1":"42.568","2":"-24.4394225"},{"1":"79.972","2":"12.9645775"},{"1":"74.663","2":"7.6555775"},{"1":"77.926","2":"10.9185775"},{"1":"48.159","2":"-18.8484225"},{"1":"49.339","2":"-17.6684225"},{"1":"80.941","2":"13.9335775"},{"1":"72.396","2":"5.3885775"},{"1":"58.556","2":"-8.4514225"},{"1":"39.613","2":"-27.3944225"},{"1":"80.884","2":"13.8765775"},{"1":"81.701","2":"14.6935775"},{"1":"74.143","2":"7.1355775"},{"1":"78.400","2":"11.3925775"},{"1":"52.517","2":"-14.4904225"},{"1":"70.616","2":"3.6085775"},{"1":"58.420","2":"-8.5874225"},{"1":"69.819","2":"2.8115775"},{"1":"73.923","2":"6.9155775"},{"1":"71.777","2":"4.7695775"},{"1":"51.542","2":"-15.4654225"},{"1":"79.425","2":"12.4175775"},{"1":"78.242","2":"11.2345775"},{"1":"76.384","2":"9.3765775"},{"1":"73.747","2":"6.7395775"},{"1":"74.249","2":"7.2415775"},{"1":"73.422","2":"6.4145775"},{"1":"62.698","2":"-4.3094225"},{"1":"42.384","2":"-24.6234225"},{"1":"43.487","2":"-23.5204225"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tabulate</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>life_expectancy_variance_table <span class="op">=</span> {</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">'life_expectancy'</span> : gapminder_2007[<span class="st">'lifeExp'</span>],</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">'diff_from_mean'</span>: gapminder_2007[<span class="st">'lifeExp'</span>]<span class="op">-</span> gapminder_2007[<span class="st">'lifeExp'</span>].mean()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>life_expectancy_variance_table <span class="op">=</span> pd.DataFrame(life_expectancy_variance_table)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(markdownTable(life_expectancy_variance_table.to_dict(orient<span class="op">=</span><span class="st">'records'</span>)).getMarkdown())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>```
+------------------------------+
|life_expectancy|diff_from_mean|
+---------------+--------------+
|     43.83     |    -23.18    |
+---------------+--------------+
|     76.42     |     9.42     |
+---------------+--------------+
|      72.3     |     5.29     |
+---------------+--------------+
|     42.73     |    -24.28    |
+---------------+--------------+
|     75.32     |     8.31     |
+---------------+--------------+
|     81.23     |     14.23    |
+---------------+--------------+
|     79.83     |     12.82    |
+---------------+--------------+
|     75.64     |     8.63     |
+---------------+--------------+
|     64.06     |     -2.95    |
+---------------+--------------+
|     79.44     |     12.43    |
+---------------+--------------+
|     56.73     |    -10.28    |
+---------------+--------------+
|     65.55     |     -1.45    |
+---------------+--------------+
|     74.85     |     7.84     |
+---------------+--------------+
|     50.73     |    -16.28    |
+---------------+--------------+
|     72.39     |     5.38     |
+---------------+--------------+
|      73.0     |      6.0     |
+---------------+--------------+
|      52.3     |    -14.71    |
+---------------+--------------+
|     49.58     |    -17.43    |
+---------------+--------------+
|     59.72     |     -7.28    |
+---------------+--------------+
|     50.43     |    -16.58    |
+---------------+--------------+
|     80.65     |     13.65    |
+---------------+--------------+
|     44.74     |    -22.27    |
+---------------+--------------+
|     50.65     |    -16.36    |
+---------------+--------------+
|     78.55     |     11.55    |
+---------------+--------------+
|     72.96     |     5.95     |
+---------------+--------------+
|     72.89     |     5.88     |
+---------------+--------------+
|     65.15     |     -1.86    |
+---------------+--------------+
|     46.46     |    -20.55    |
+---------------+--------------+
|     55.32     |    -11.69    |
+---------------+--------------+
|     78.78     |     11.77    |
+---------------+--------------+
|     48.33     |    -18.68    |
+---------------+--------------+
|     75.75     |     8.74     |
+---------------+--------------+
|     78.27     |     11.27    |
+---------------+--------------+
|     76.49     |     9.48     |
+---------------+--------------+
|     78.33     |     11.32    |
+---------------+--------------+
|     54.79     |    -12.22    |
+---------------+--------------+
|     72.23     |     5.23     |
+---------------+--------------+
|     74.99     |     7.99     |
+---------------+--------------+
|     71.34     |     4.33     |
+---------------+--------------+
|     71.88     |     4.87     |
+---------------+--------------+
|     51.58     |    -15.43    |
+---------------+--------------+
|     58.04     |     -8.97    |
+---------------+--------------+
|     52.95     |    -14.06    |
+---------------+--------------+
|     79.31     |     12.31    |
+---------------+--------------+
|     80.66     |     13.65    |
+---------------+--------------+
|     56.73     |    -10.27    |
+---------------+--------------+
|     59.45     |     -7.56    |
+---------------+--------------+
|     79.41     |     12.4     |
+---------------+--------------+
|     60.02     |     -6.99    |
+---------------+--------------+
|     79.48     |     12.48    |
+---------------+--------------+
|     70.26     |     3.25     |
+---------------+--------------+
|     56.01     |     -11.0    |
+---------------+--------------+
|     46.39     |    -20.62    |
+---------------+--------------+
|     60.92     |     -6.09    |
+---------------+--------------+
|      70.2     |     3.19     |
+---------------+--------------+
|     82.21     |     15.2     |
+---------------+--------------+
|     73.34     |     6.33     |
+---------------+--------------+
|     81.76     |     14.75    |
+---------------+--------------+
|      64.7     |     -2.31    |
+---------------+--------------+
|     70.65     |     3.64     |
+---------------+--------------+
|     70.96     |     3.96     |
+---------------+--------------+
|     59.55     |     -7.46    |
+---------------+--------------+
|     78.89     |     11.88    |
+---------------+--------------+
|     80.75     |     13.74    |
+---------------+--------------+
|     80.55     |     13.54    |
+---------------+--------------+
|     72.57     |     5.56     |
+---------------+--------------+
|      82.6     |     15.6     |
+---------------+--------------+
|     72.53     |     5.53     |
+---------------+--------------+
|     54.11     |     -12.9    |
+---------------+--------------+
|      67.3     |     0.29     |
+---------------+--------------+
|     78.62     |     11.62    |
+---------------+--------------+
|     77.59     |     10.58    |
+---------------+--------------+
|     71.99     |     4.99     |
+---------------+--------------+
|     42.59     |    -24.42    |
+---------------+--------------+
|     45.68     |    -21.33    |
+---------------+--------------+
|     73.95     |     6.94     |
+---------------+--------------+
|     59.44     |     -7.56    |
+---------------+--------------+
|      48.3     |     -18.7    |
+---------------+--------------+
|     74.24     |     7.23     |
+---------------+--------------+
|     54.47     |    -12.54    |
+---------------+--------------+
|     64.16     |     -2.84    |
+---------------+--------------+
|      72.8     |     5.79     |
+---------------+--------------+
|     76.19     |     9.19     |
+---------------+--------------+
|      66.8     |     -0.2     |
+---------------+--------------+
|     74.54     |     7.54     |
+---------------+--------------+
|     71.16     |     4.16     |
+---------------+--------------+
|     42.08     |    -24.93    |
+---------------+--------------+
|     62.07     |     -4.94    |
+---------------+--------------+
|     52.91     |     -14.1    |
+---------------+--------------+
|     63.78     |     -3.22    |
+---------------+--------------+
|     79.76     |     12.75    |
+---------------+--------------+
|      80.2     |     13.2     |
+---------------+--------------+
|      72.9     |     5.89     |
+---------------+--------------+
|     56.87     |    -10.14    |
+---------------+--------------+
|     46.86     |    -20.15    |
+---------------+--------------+
|      80.2     |     13.19    |
+---------------+--------------+
|     75.64     |     8.63     |
+---------------+--------------+
|     65.48     |     -1.52    |
+---------------+--------------+
|     75.54     |     8.53     |
+---------------+--------------+
|     71.75     |     4.74     |
+---------------+--------------+
|     71.42     |     4.41     |
+---------------+--------------+
|     71.69     |     4.68     |
+---------------+--------------+
|     75.56     |     8.56     |
+---------------+--------------+
|      78.1     |     11.09    |
+---------------+--------------+
|     78.75     |     11.74    |
+---------------+--------------+
|     76.44     |     9.43     |
+---------------+--------------+
|     72.48     |     5.47     |
+---------------+--------------+
|     46.24     |    -20.77    |
+---------------+--------------+
|     65.53     |     -1.48    |
+---------------+--------------+
|     72.78     |     5.77     |
+---------------+--------------+
|     63.06     |     -3.95    |
+---------------+--------------+
|      74.0     |     6.99     |
+---------------+--------------+
|     42.57     |    -24.44    |
+---------------+--------------+
|     79.97     |     12.96    |
+---------------+--------------+
|     74.66     |     7.66     |
+---------------+--------------+
|     77.93     |     10.92    |
+---------------+--------------+
|     48.16     |    -18.85    |
+---------------+--------------+
|     49.34     |    -17.67    |
+---------------+--------------+
|     80.94     |     13.93    |
+---------------+--------------+
|      72.4     |     5.39     |
+---------------+--------------+
|     58.56     |     -8.45    |
+---------------+--------------+
|     39.61     |    -27.39    |
+---------------+--------------+
|     80.88     |     13.88    |
+---------------+--------------+
|      81.7     |     14.69    |
+---------------+--------------+
|     74.14     |     7.14     |
+---------------+--------------+
|      78.4     |     11.39    |
+---------------+--------------+
|     52.52     |    -14.49    |
+---------------+--------------+
|     70.62     |     3.61     |
+---------------+--------------+
|     58.42     |     -8.59    |
+---------------+--------------+
|     69.82     |     2.81     |
+---------------+--------------+
|     73.92     |     6.92     |
+---------------+--------------+
|     71.78     |     4.77     |
+---------------+--------------+
|     51.54     |    -15.47    |
+---------------+--------------+
|     79.42     |     12.42    |
+---------------+--------------+
|     78.24     |     11.23    |
+---------------+--------------+
|     76.38     |     9.38     |
+---------------+--------------+
|     73.75     |     6.74     |
+---------------+--------------+
|     74.25     |     7.24     |
+---------------+--------------+
|     73.42     |     6.41     |
+---------------+--------------+
|      62.7     |     -4.31    |
+---------------+--------------+
|     42.38     |    -24.62    |
+---------------+--------------+
|     43.49     |    -23.52    |
+------------------------------+```</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>So we know for <strong>each</strong> country how different their life expectacy is to the mean life expectancy. But ideally we would like a single value to summarise variance. Lets see what would happen if we tried to summarise these differences from the mean by calculating the mean difference from the mean:</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(life_expectancy_variance_table<span class="sc">$</span>diff_from_mean) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.153937e-15</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_variance_table[<span class="st">'diff_from_mean'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>5.254013186958487e-15</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>We get a number that is effectively zero (go <a href="../statsBasics/eNumbers.html" target="_blank">here</a> for an explanation about e-numbers), because all the values above the mean balance out those below the mean. So to address this, we can square the differences to force all the numbers to be positive:</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_variance_table<span class="sc">$</span>diff_squared <span class="ot">=</span> life_expectancy_variance_table<span class="sc">$</span>diff_from_mean<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>rmarkdown<span class="sc">::</span><span class="fu">paged_table</span>(life_expectancy_variance_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["life_expectancy"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["diff_from_mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["diff_squared"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"43.828","2":"-23.1794225","3":"537.28562907"},{"1":"76.423","2":"9.4155775","3":"88.65309900"},{"1":"72.301","2":"5.2935775","3":"28.02196238"},{"1":"42.731","2":"-24.2764225","3":"589.34469111"},{"1":"75.320","2":"8.3125775","3":"69.09894411"},{"1":"81.235","2":"14.2275775","3":"202.42396052"},{"1":"79.829","2":"12.8215775","3":"164.39284869"},{"1":"75.635","2":"8.6275775","3":"74.43509291"},{"1":"64.062","2":"-2.9454225","3":"8.67551391"},{"1":"79.441","2":"12.4335775","3":"154.59384857"},{"1":"56.728","2":"-10.2794225","3":"105.66652766"},{"1":"65.554","2":"-1.4534225","3":"2.11243707"},{"1":"74.852","2":"7.8445775","3":"61.53739560"},{"1":"50.728","2":"-16.2794225","3":"265.01959808"},{"1":"72.390","2":"5.3825775","3":"28.97214016"},{"1":"73.005","2":"5.9975775","3":"35.97093545"},{"1":"52.295","2":"-14.7124225","3":"216.45537685"},{"1":"49.580","2":"-17.4274225","3":"303.71505622"},{"1":"59.723","2":"-7.2844225","3":"53.06281167"},{"1":"50.430","2":"-16.5774225","3":"274.81093791"},{"1":"80.653","2":"13.6455775","3":"186.20178435"},{"1":"44.741","2":"-22.2664225","3":"495.79357252"},{"1":"50.651","2":"-16.3564225","3":"267.53255815"},{"1":"78.553","2":"11.5455775","3":"133.30035900"},{"1":"72.961","2":"5.9535775","3":"35.44508463"},{"1":"72.889","2":"5.8815775","3":"34.59295347"},{"1":"65.152","2":"-1.8554225","3":"3.44259278"},{"1":"46.462","2":"-20.5454225","3":"422.11438715"},{"1":"55.322","2":"-11.6854225","3":"136.54909983"},{"1":"78.782","2":"11.7745775","3":"138.64067447"},{"1":"48.328","2":"-18.6794225","3":"348.92082625"},{"1":"75.748","2":"8.7405775","3":"76.39769442"},{"1":"78.273","2":"11.2655775","3":"126.91323562"},{"1":"76.486","2":"9.4785775","3":"89.84343076"},{"1":"78.332","2":"11.3245775","3":"128.24605476"},{"1":"54.791","2":"-12.2164225","3":"149.24097956"},{"1":"72.235","2":"5.2275775","3":"27.32756615"},{"1":"74.994","2":"7.9865775","3":"63.78541960"},{"1":"71.338","2":"4.3305775","3":"18.75390118"},{"1":"71.878","2":"4.8705775","3":"23.72252484"},{"1":"51.579","2":"-15.4284225","3":"238.03622193"},{"1":"58.040","2":"-8.9674225","3":"80.41466693"},{"1":"52.947","2":"-14.0604225","3":"197.69548187"},{"1":"79.313","2":"12.3055775","3":"151.42723674"},{"1":"80.657","2":"13.6495775","3":"186.31096497"},{"1":"56.735","2":"-10.2724225","3":"105.52266474"},{"1":"59.448","2":"-7.5594225","3":"57.14486907"},{"1":"79.406","2":"12.3985775","3":"153.72472315"},{"1":"60.022","2":"-6.9854225","3":"48.79612800"},{"1":"79.483","2":"12.4755775","3":"155.64003308"},{"1":"70.259","2":"3.2515775","3":"10.57275601"},{"1":"56.007","2":"-11.0004225","3":"121.00929595"},{"1":"46.388","2":"-20.6194225","3":"425.16058569"},{"1":"60.916","2":"-6.0914225","3":"37.10542850"},{"1":"70.198","2":"3.1905775","3":"10.17978456"},{"1":"82.208","2":"15.2005775","3":"231.05755526"},{"1":"73.338","2":"6.3305775","3":"40.07621104"},{"1":"81.757","2":"14.7495775","3":"217.55003539"},{"1":"64.698","2":"-2.3094225","3":"5.33343245"},{"1":"70.650","2":"3.6425775","3":"13.26837059"},{"1":"70.964","2":"3.9565775","3":"15.65450523"},{"1":"59.545","2":"-7.4624225","3":"55.68775009"},{"1":"78.885","2":"11.8775775","3":"141.07684643"},{"1":"80.745","2":"13.7375775","3":"188.72103460"},{"1":"80.546","2":"13.5385775","3":"183.29307977"},{"1":"72.567","2":"5.5595775","3":"30.90890159"},{"1":"82.603","2":"15.5955775","3":"243.22203646"},{"1":"72.535","2":"5.5275775","3":"30.55411263"},{"1":"54.110","2":"-12.8974225","3":"166.34350805"},{"1":"67.297","2":"0.2895775","3":"0.08385511"},{"1":"78.623","2":"11.6155775","3":"134.92163984"},{"1":"77.588","2":"10.5805775","3":"111.94861949"},{"1":"71.993","2":"4.9855775","3":"24.85598266"},{"1":"42.592","2":"-24.4154225","3":"596.11285757"},{"1":"45.678","2":"-21.3294225","3":"454.94426569"},{"1":"73.952","2":"6.9445775","3":"48.22715616"},{"1":"59.443","2":"-7.5644225","3":"57.22048829"},{"1":"48.303","2":"-18.7044225","3":"349.85542238"},{"1":"74.241","2":"7.2335775","3":"52.32464294"},{"1":"54.467","2":"-12.5404225","3":"157.26219736"},{"1":"64.164","2":"-2.8434225","3":"8.08505171"},{"1":"72.801","2":"5.7935775","3":"33.56553984"},{"1":"76.195","2":"9.1875775","3":"84.41157967"},{"1":"66.803","2":"-0.2044225","3":"0.04178857"},{"1":"74.543","2":"7.5355775","3":"56.78492773"},{"1":"71.164","2":"4.1565775","3":"17.27713622"},{"1":"42.082","2":"-24.9254225","3":"621.27668856"},{"1":"62.069","2":"-4.9384225","3":"24.38801714"},{"1":"52.906","2":"-14.1014225","3":"198.85011752"},{"1":"63.785","2":"-3.2224225","3":"10.38400700"},{"1":"79.762","2":"12.7545775","3":"162.67924631"},{"1":"80.204","2":"13.1965775","3":"174.14965678"},{"1":"72.899","2":"5.8915775","3":"34.71068502"},{"1":"56.867","2":"-10.1404225","3":"102.82816919"},{"1":"46.859","2":"-20.1484225","3":"405.95893066"},{"1":"80.196","2":"13.1885775","3":"173.93857554"},{"1":"75.640","2":"8.6325775","3":"74.52139369"},{"1":"65.483","2":"-1.5244225","3":"2.32386407"},{"1":"75.537","2":"8.5295775","3":"72.75369173"},{"1":"71.752","2":"4.7445775","3":"22.51101532"},{"1":"71.421","2":"4.4135775","3":"19.47966604"},{"1":"71.688","2":"4.6805775","3":"21.90780540"},{"1":"75.563","2":"8.5555775","3":"73.19790576"},{"1":"78.098","2":"11.0905775","3":"123.00090850"},{"1":"78.746","2":"11.7385775","3":"137.79420090"},{"1":"76.442","2":"9.4345775","3":"89.01125194"},{"1":"72.476","2":"5.4685775","3":"29.90533949"},{"1":"46.242","2":"-20.7654225","3":"431.20277307"},{"1":"65.528","2":"-1.4794225","3":"2.18869104"},{"1":"72.777","2":"5.7695775","3":"33.28802412"},{"1":"63.062","2":"-3.9454225","3":"15.56635898"},{"1":"74.002","2":"6.9945775","3":"48.92411391"},{"1":"42.568","2":"-24.4394225","3":"597.28537385"},{"1":"79.972","2":"12.9645775","3":"168.08026884"},{"1":"74.663","2":"7.6555775","3":"58.60786632"},{"1":"77.926","2":"10.9185775","3":"119.21533385"},{"1":"48.159","2":"-18.8484225","3":"355.26303207"},{"1":"49.339","2":"-17.6684225","3":"312.17315488"},{"1":"80.941","2":"13.9335775","3":"194.14458097"},{"1":"72.396","2":"5.3885775","3":"29.03676709"},{"1":"58.556","2":"-8.4514225","3":"71.42654287"},{"1":"39.613","2":"-27.3944225","3":"750.45438604"},{"1":"80.884","2":"13.8765775","3":"192.55940214"},{"1":"81.701","2":"14.6935775","3":"215.90121871"},{"1":"74.143","2":"7.1355775","3":"50.91646576"},{"1":"78.400","2":"11.3925775","3":"129.79082129"},{"1":"52.517","2":"-14.4904225","3":"209.97234525"},{"1":"70.616","2":"3.6085775","3":"13.02183132"},{"1":"58.420","2":"-8.5874225","3":"73.74382580"},{"1":"69.819","2":"2.8115775","3":"7.90496784"},{"1":"73.923","2":"6.9155775","3":"47.82521167"},{"1":"71.777","2":"4.7695775","3":"22.74886919"},{"1":"51.542","2":"-15.4654225","3":"239.17929419"},{"1":"79.425","2":"12.4175775","3":"154.19623009"},{"1":"78.242","2":"11.2345775","3":"126.21573081"},{"1":"76.384","2":"9.3765775","3":"87.92020495"},{"1":"73.747","2":"6.7395775","3":"45.42190440"},{"1":"74.249","2":"7.2415775","3":"52.44044418"},{"1":"73.422","2":"6.4145775","3":"41.14680405"},{"1":"62.698","2":"-4.3094225","3":"18.57112259"},{"1":"42.384","2":"-24.6234225","3":"606.31293735"},{"1":"43.487","2":"-23.5204225","3":"553.21027623"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_variance_table[<span class="st">'diff_squared'</span>] <span class="op">=</span> life_expectancy_variance_table[<span class="st">'diff_from_mean'</span>].<span class="bu">pow</span>(<span class="dv">2</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(markdownTable(life_expectancy_variance_table.to_dict(orient<span class="op">=</span><span class="st">'records'</span>)).getMarkdown())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>```
+-------------------------------------------+
|life_expectancy|diff_from_mean|diff_squared|
+---------------+--------------+------------+
|     43.83     |    -23.18    |   537.29   |
+---------------+--------------+------------+
|     76.42     |     9.42     |    88.65   |
+---------------+--------------+------------+
|      72.3     |     5.29     |    28.02   |
+---------------+--------------+------------+
|     42.73     |    -24.28    |   589.34   |
+---------------+--------------+------------+
|     75.32     |     8.31     |    69.1    |
+---------------+--------------+------------+
|     81.23     |     14.23    |   202.42   |
+---------------+--------------+------------+
|     79.83     |     12.82    |   164.39   |
+---------------+--------------+------------+
|     75.64     |     8.63     |    74.44   |
+---------------+--------------+------------+
|     64.06     |     -2.95    |    8.68    |
+---------------+--------------+------------+
|     79.44     |     12.43    |   154.59   |
+---------------+--------------+------------+
|     56.73     |    -10.28    |   105.67   |
+---------------+--------------+------------+
|     65.55     |     -1.45    |    2.11    |
+---------------+--------------+------------+
|     74.85     |     7.84     |    61.54   |
+---------------+--------------+------------+
|     50.73     |    -16.28    |   265.02   |
+---------------+--------------+------------+
|     72.39     |     5.38     |    28.97   |
+---------------+--------------+------------+
|      73.0     |      6.0     |    35.97   |
+---------------+--------------+------------+
|      52.3     |    -14.71    |   216.46   |
+---------------+--------------+------------+
|     49.58     |    -17.43    |   303.72   |
+---------------+--------------+------------+
|     59.72     |     -7.28    |    53.06   |
+---------------+--------------+------------+
|     50.43     |    -16.58    |   274.81   |
+---------------+--------------+------------+
|     80.65     |     13.65    |    186.2   |
+---------------+--------------+------------+
|     44.74     |    -22.27    |   495.79   |
+---------------+--------------+------------+
|     50.65     |    -16.36    |   267.53   |
+---------------+--------------+------------+
|     78.55     |     11.55    |    133.3   |
+---------------+--------------+------------+
|     72.96     |     5.95     |    35.45   |
+---------------+--------------+------------+
|     72.89     |     5.88     |    34.59   |
+---------------+--------------+------------+
|     65.15     |     -1.86    |    3.44    |
+---------------+--------------+------------+
|     46.46     |    -20.55    |   422.11   |
+---------------+--------------+------------+
|     55.32     |    -11.69    |   136.55   |
+---------------+--------------+------------+
|     78.78     |     11.77    |   138.64   |
+---------------+--------------+------------+
|     48.33     |    -18.68    |   348.92   |
+---------------+--------------+------------+
|     75.75     |     8.74     |    76.4    |
+---------------+--------------+------------+
|     78.27     |     11.27    |   126.91   |
+---------------+--------------+------------+
|     76.49     |     9.48     |    89.84   |
+---------------+--------------+------------+
|     78.33     |     11.32    |   128.25   |
+---------------+--------------+------------+
|     54.79     |    -12.22    |   149.24   |
+---------------+--------------+------------+
|     72.23     |     5.23     |    27.33   |
+---------------+--------------+------------+
|     74.99     |     7.99     |    63.79   |
+---------------+--------------+------------+
|     71.34     |     4.33     |    18.75   |
+---------------+--------------+------------+
|     71.88     |     4.87     |    23.72   |
+---------------+--------------+------------+
|     51.58     |    -15.43    |   238.04   |
+---------------+--------------+------------+
|     58.04     |     -8.97    |    80.41   |
+---------------+--------------+------------+
|     52.95     |    -14.06    |    197.7   |
+---------------+--------------+------------+
|     79.31     |     12.31    |   151.43   |
+---------------+--------------+------------+
|     80.66     |     13.65    |   186.31   |
+---------------+--------------+------------+
|     56.73     |    -10.27    |   105.52   |
+---------------+--------------+------------+
|     59.45     |     -7.56    |    57.14   |
+---------------+--------------+------------+
|     79.41     |     12.4     |   153.72   |
+---------------+--------------+------------+
|     60.02     |     -6.99    |    48.8    |
+---------------+--------------+------------+
|     79.48     |     12.48    |   155.64   |
+---------------+--------------+------------+
|     70.26     |     3.25     |    10.57   |
+---------------+--------------+------------+
|     56.01     |     -11.0    |   121.01   |
+---------------+--------------+------------+
|     46.39     |    -20.62    |   425.16   |
+---------------+--------------+------------+
|     60.92     |     -6.09    |    37.11   |
+---------------+--------------+------------+
|      70.2     |     3.19     |    10.18   |
+---------------+--------------+------------+
|     82.21     |     15.2     |   231.06   |
+---------------+--------------+------------+
|     73.34     |     6.33     |    40.08   |
+---------------+--------------+------------+
|     81.76     |     14.75    |   217.55   |
+---------------+--------------+------------+
|      64.7     |     -2.31    |    5.33    |
+---------------+--------------+------------+
|     70.65     |     3.64     |    13.27   |
+---------------+--------------+------------+
|     70.96     |     3.96     |    15.65   |
+---------------+--------------+------------+
|     59.55     |     -7.46    |    55.69   |
+---------------+--------------+------------+
|     78.89     |     11.88    |   141.08   |
+---------------+--------------+------------+
|     80.75     |     13.74    |   188.72   |
+---------------+--------------+------------+
|     80.55     |     13.54    |   183.29   |
+---------------+--------------+------------+
|     72.57     |     5.56     |    30.91   |
+---------------+--------------+------------+
|      82.6     |     15.6     |   243.22   |
+---------------+--------------+------------+
|     72.53     |     5.53     |    30.55   |
+---------------+--------------+------------+
|     54.11     |     -12.9    |   166.34   |
+---------------+--------------+------------+
|      67.3     |     0.29     |    0.08    |
+---------------+--------------+------------+
|     78.62     |     11.62    |   134.92   |
+---------------+--------------+------------+
|     77.59     |     10.58    |   111.95   |
+---------------+--------------+------------+
|     71.99     |     4.99     |    24.86   |
+---------------+--------------+------------+
|     42.59     |    -24.42    |   596.11   |
+---------------+--------------+------------+
|     45.68     |    -21.33    |   454.94   |
+---------------+--------------+------------+
|     73.95     |     6.94     |    48.23   |
+---------------+--------------+------------+
|     59.44     |     -7.56    |    57.22   |
+---------------+--------------+------------+
|      48.3     |     -18.7    |   349.86   |
+---------------+--------------+------------+
|     74.24     |     7.23     |    52.32   |
+---------------+--------------+------------+
|     54.47     |    -12.54    |   157.26   |
+---------------+--------------+------------+
|     64.16     |     -2.84    |    8.09    |
+---------------+--------------+------------+
|      72.8     |     5.79     |    33.57   |
+---------------+--------------+------------+
|     76.19     |     9.19     |    84.41   |
+---------------+--------------+------------+
|      66.8     |     -0.2     |    0.04    |
+---------------+--------------+------------+
|     74.54     |     7.54     |    56.78   |
+---------------+--------------+------------+
|     71.16     |     4.16     |    17.28   |
+---------------+--------------+------------+
|     42.08     |    -24.93    |   621.28   |
+---------------+--------------+------------+
|     62.07     |     -4.94    |    24.39   |
+---------------+--------------+------------+
|     52.91     |     -14.1    |   198.85   |
+---------------+--------------+------------+
|     63.78     |     -3.22    |    10.38   |
+---------------+--------------+------------+
|     79.76     |     12.75    |   162.68   |
+---------------+--------------+------------+
|      80.2     |     13.2     |   174.15   |
+---------------+--------------+------------+
|      72.9     |     5.89     |    34.71   |
+---------------+--------------+------------+
|     56.87     |    -10.14    |   102.83   |
+---------------+--------------+------------+
|     46.86     |    -20.15    |   405.96   |
+---------------+--------------+------------+
|      80.2     |     13.19    |   173.94   |
+---------------+--------------+------------+
|     75.64     |     8.63     |    74.52   |
+---------------+--------------+------------+
|     65.48     |     -1.52    |    2.32    |
+---------------+--------------+------------+
|     75.54     |     8.53     |    72.75   |
+---------------+--------------+------------+
|     71.75     |     4.74     |    22.51   |
+---------------+--------------+------------+
|     71.42     |     4.41     |    19.48   |
+---------------+--------------+------------+
|     71.69     |     4.68     |    21.91   |
+---------------+--------------+------------+
|     75.56     |     8.56     |    73.2    |
+---------------+--------------+------------+
|      78.1     |     11.09    |    123.0   |
+---------------+--------------+------------+
|     78.75     |     11.74    |   137.79   |
+---------------+--------------+------------+
|     76.44     |     9.43     |    89.01   |
+---------------+--------------+------------+
|     72.48     |     5.47     |    29.91   |
+---------------+--------------+------------+
|     46.24     |    -20.77    |    431.2   |
+---------------+--------------+------------+
|     65.53     |     -1.48    |    2.19    |
+---------------+--------------+------------+
|     72.78     |     5.77     |    33.29   |
+---------------+--------------+------------+
|     63.06     |     -3.95    |    15.57   |
+---------------+--------------+------------+
|      74.0     |     6.99     |    48.92   |
+---------------+--------------+------------+
|     42.57     |    -24.44    |   597.29   |
+---------------+--------------+------------+
|     79.97     |     12.96    |   168.08   |
+---------------+--------------+------------+
|     74.66     |     7.66     |    58.61   |
+---------------+--------------+------------+
|     77.93     |     10.92    |   119.22   |
+---------------+--------------+------------+
|     48.16     |    -18.85    |   355.26   |
+---------------+--------------+------------+
|     49.34     |    -17.67    |   312.17   |
+---------------+--------------+------------+
|     80.94     |     13.93    |   194.14   |
+---------------+--------------+------------+
|      72.4     |     5.39     |    29.04   |
+---------------+--------------+------------+
|     58.56     |     -8.45    |    71.43   |
+---------------+--------------+------------+
|     39.61     |    -27.39    |   750.45   |
+---------------+--------------+------------+
|     80.88     |     13.88    |   192.56   |
+---------------+--------------+------------+
|      81.7     |     14.69    |    215.9   |
+---------------+--------------+------------+
|     74.14     |     7.14     |    50.92   |
+---------------+--------------+------------+
|      78.4     |     11.39    |   129.79   |
+---------------+--------------+------------+
|     52.52     |    -14.49    |   209.97   |
+---------------+--------------+------------+
|     70.62     |     3.61     |    13.02   |
+---------------+--------------+------------+
|     58.42     |     -8.59    |    73.74   |
+---------------+--------------+------------+
|     69.82     |     2.81     |     7.9    |
+---------------+--------------+------------+
|     73.92     |     6.92     |    47.83   |
+---------------+--------------+------------+
|     71.78     |     4.77     |    22.75   |
+---------------+--------------+------------+
|     51.54     |    -15.47    |   239.18   |
+---------------+--------------+------------+
|     79.42     |     12.42    |    154.2   |
+---------------+--------------+------------+
|     78.24     |     11.23    |   126.22   |
+---------------+--------------+------------+
|     76.38     |     9.38     |    87.92   |
+---------------+--------------+------------+
|     73.75     |     6.74     |    45.42   |
+---------------+--------------+------------+
|     74.25     |     7.24     |    52.44   |
+---------------+--------------+------------+
|     73.42     |     6.41     |    41.15   |
+---------------+--------------+------------+
|      62.7     |     -4.31    |    18.57   |
+---------------+--------------+------------+
|     42.38     |    -24.62    |   606.31   |
+---------------+--------------+------------+
|     43.49     |    -23.52    |   553.21   |
+-------------------------------------------+```</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>If we calculate the average of this, then we get a summary of the variance that is more informative:</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(life_expectancy_variance_table<span class="sc">$</span>diff_squared)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 144.7314</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_variance_table[<span class="st">'diff_squared'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>144.73136049752028</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>However, as mean is what you get when you add all the items together and then divide it by the number of items, this can also be done in 2 steps in R (this will help us understand the formula later):</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sum_of_squares <span class="ot">=</span> <span class="fu">sum</span>(life_expectancy_variance_table<span class="sc">$</span>diff_squared)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>this_variance  <span class="ot">=</span> sum_of_squares<span class="sc">/</span><span class="fu">length</span>(life_expectancy_variance_table<span class="sc">$</span>diff_squared)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>this_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 144.7314</code></pre>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sum_of_squares <span class="op">=</span> life_expectancy_variance_table[<span class="st">'diff_squared'</span>].<span class="bu">sum</span>()</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>this_variance <span class="op">=</span> sum_of_squares<span class="op">/</span>life_expectancy_variance_table[<span class="st">'diff_squared'</span>].count()</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>this_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>144.73136049752028</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>We can represent the above in the following formula for the <strong>population</strong>’s (remember, this is when you have everyone from the group you are measuring) variance:</p>
<p><span class="math display">\[
\sigma^2 = \frac{\sum((x_i- \bar{x}{} )^2)} {N}
\]</span></p>
<p>Let’s break down each of the above symbols: σ^2 is population variance Σ is sum <strong>x</strong>i refers to the value for each participant x̄ refers to the mean for all participants N refers to the number of participants</p>
<p><strong>(note that the above is written as if we’re looking at the variance of a group of participants, but the principles still work if looking at non-participant data)</strong></p>
</section>
<section id="sample-variance" class="level3">
<h3 class="anchored" data-anchor-id="sample-variance">Sample variance</h3>
<p>To calculate the variance for a <strong>sample</strong> of participants, rather than every participant in the group you’re measuring, you need a slightly different formula:</p>
<p><span class="math display">\[
S^2 = \frac{\sum((x_i- \bar{x}{} )^2)} {N - 1}
\]</span> <em>Note that Sample variance is represented by S^2 rather than σ^2</em></p>
<p>So why do we divide by N-1 rather than N? This is because the sample variance is an <em>estimate</em> rather than the actual population variance. When estimating the population variance you take into account the actual number of people (N) in the sample, whereas when you are estimating what happens generally in the population based on your sample, you take into account the <strong>degrees of freedom</strong> (N-1). In broad terms this reduces the risk of you under-estimating the variance of the population. You don’t necessarily need to understand <strong>degrees of freedom</strong> beyond the idea that you are controlling for the fact that you are analysing a sample rather than the population they represent, <em>so don’t worry if the next section isn’t completely clear</em>.</p>
</section>
</section>
<section id="degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h2>
<p>Degrees of freedom calculations can be useful to address statistics that are vulnerable to bias within a sample (i.e.&nbsp;the sample being distorted compared to the population). Interestingly, <strong>mean</strong> is not, but <strong>variance</strong> is. Lets see this by looking at differences between the population and sample for mean and variance, looking at the height of three people, and combining them into every combination of 2 people possible:</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>three_heights <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">150</span>,<span class="dv">160</span>,<span class="dv">170</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>population_height_mean <span class="ot">=</span> <span class="fu">mean</span>(three_heights)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>population_height_variance <span class="ot">=</span> <span class="fu">sum</span>((three_heights <span class="sc">-</span> population_height_mean)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">3</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">#sample participants in pairs</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>sample_heights <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pp1 =</span> <span class="fu">c</span>(<span class="dv">150</span>,<span class="dv">150</span>,<span class="cn">NA</span>),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">pp2 =</span> <span class="fu">c</span>(<span class="dv">160</span>,<span class="cn">NA</span>,<span class="dv">160</span>),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">pp3 =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">170</span>,<span class="dv">170</span>),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">pair =</span> <span class="fu">c</span>(</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"1 and 2"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"1 and 3"</span>,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"2 and 3"</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>sample_heights<span class="sc">$</span>mean <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">2</span>])),</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">3</span>])),</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">2</span>], three_heights[<span class="dv">3</span>]))</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>sample_heights<span class="sc">$</span>pop_var <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">2</span>]) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">2</span>])))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">3</span>,</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">3</span>]) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">3</span>])))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">3</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((<span class="fu">c</span>(three_heights[<span class="dv">2</span>], three_heights[<span class="dv">3</span>]) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">2</span>], three_heights[<span class="dv">3</span>])))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">3</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>sample_heights<span class="sc">$</span>sample_var <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">2</span>]) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">2</span>])))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="dv">3-1</span>),</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">3</span>]) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">1</span>], three_heights[<span class="dv">3</span>])))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="dv">3-1</span>),</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((<span class="fu">c</span>(three_heights[<span class="dv">2</span>], three_heights[<span class="dv">3</span>]) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">c</span>(three_heights[<span class="dv">2</span>], three_heights[<span class="dv">3</span>])))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="dv">3-1</span>)</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>rmarkdown<span class="sc">::</span><span class="fu">paged_table</span>(sample_heights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["pp1"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["pp2"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["pp3"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["pair"],"name":[4],"type":["chr"],"align":["left"]},{"label":["mean"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["pop_var"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["sample_var"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"150","2":"160","3":"NA","4":"1 and 2","5":"155","6":"16.66667","7":"25"},{"1":"150","2":"NA","3":"170","4":"1 and 3","5":"160","6":"66.66667","7":"100"},{"1":"NA","2":"160","3":"170","4":"2 and 3","5":"165","6":"16.66667","7":"25"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mean_sample_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_heights<span class="sc">$</span>mean)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mean_sample_variance <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_heights<span class="sc">$</span>sample_var)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>mean_population_variance <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_heights<span class="sc">$</span>pop_var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>three_heights <span class="op">=</span> [<span class="dv">150</span>,<span class="dv">160</span>,<span class="dv">170</span>]</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>three_heights <span class="op">=</span> pd.DataFrame(three_heights)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>population_height_mean <span class="op">=</span> three_heights.mean()</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>population_height_variance <span class="op">=</span> (three_heights <span class="op">-</span> population_height_mean).<span class="bu">pow</span>(<span class="dv">2</span>).<span class="bu">sum</span>()<span class="op">/</span><span class="dv">3</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#sample participants in pairs</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>sample_heights <span class="op">=</span> {</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">'pp1'</span>: [<span class="dv">150</span>,<span class="dv">150</span>, np.nan],</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">'pp2'</span>: [<span class="dv">160</span>, np.nan, <span class="dv">160</span>],</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">'pp3'</span>: [np.nan, <span class="dv">170</span>, <span class="dv">170</span>],</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">'pair'</span>: [<span class="st">"1 and 2"</span>, <span class="st">"1 and 3"</span>, <span class="st">"2 and 3"</span>]</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>sample_heights <span class="op">=</span> pd.DataFrame(sample_heights)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>mean <span class="op">=</span> [three_heights.iloc[<span class="dv">0</span>:<span class="dv">2</span>].mean(),three_heights.iloc[[<span class="dv">0</span>,<span class="dv">2</span>],].mean(),three_heights.iloc[<span class="dv">1</span>:<span class="dv">3</span>].mean()]</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>mean <span class="op">=</span> pd.DataFrame(mean)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>sample_heights[<span class="st">'mean'</span>]<span class="op">=</span>mean</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>pop_var<span class="op">=</span>[((three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">0</span>:<span class="dv">2</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>) <span class="op">+</span> (three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">0</span>:<span class="dv">2</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>))<span class="op">/</span><span class="dv">3</span>,((three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[[<span class="dv">0</span>,<span class="dv">2</span>],].mean()).<span class="bu">pow</span>(<span class="dv">2</span>) <span class="op">+</span> (three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[[<span class="dv">0</span>,<span class="dv">2</span>],].mean()).<span class="bu">pow</span>(<span class="dv">2</span>))<span class="op">/</span><span class="dv">3</span>,((three_heights.iloc[<span class="dv">1</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">1</span>:<span class="dv">3</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>) <span class="op">+</span> (three_heights.iloc[<span class="dv">2</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">1</span>:<span class="dv">3</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>))<span class="op">/</span><span class="dv">3</span>]</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>pop_var <span class="op">=</span> pd.DataFrame(pop_var)</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>sample_heights[<span class="st">'pop_var'</span>]<span class="op">=</span> pop_var</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>sample_var<span class="op">=</span>[((three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">0</span>:<span class="dv">2</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>) <span class="op">+</span> (three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">0</span>:<span class="dv">2</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>))<span class="op">/</span>(<span class="dv">3</span><span class="op">-</span><span class="dv">1</span>),((three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[[<span class="dv">0</span>,<span class="dv">2</span>],].mean()).<span class="bu">pow</span>(<span class="dv">2</span>) <span class="op">+</span> (three_heights.iloc[<span class="dv">0</span>] <span class="op">-</span> three_heights.iloc[[<span class="dv">0</span>,<span class="dv">2</span>],].mean()).<span class="bu">pow</span>(<span class="dv">2</span>))<span class="op">/</span>(<span class="dv">3</span><span class="op">-</span><span class="dv">1</span>),((three_heights.iloc[<span class="dv">1</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">1</span>:<span class="dv">3</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>) <span class="op">+</span> (three_heights.iloc[<span class="dv">2</span>] <span class="op">-</span> three_heights.iloc[<span class="dv">1</span>:<span class="dv">3</span>].mean()).<span class="bu">pow</span>(<span class="dv">2</span>))<span class="op">/</span>(<span class="dv">3</span><span class="op">-</span><span class="dv">1</span>)]</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>sample_var<span class="op">=</span>pd.DataFrame(sample_var)</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>sample_heights[<span class="st">'sample_var'</span>]<span class="op">=</span>sample_var</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>sample_heights <span class="op">=</span> pd.DataFrame(sample_heights)</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(markdownTable(sample_heights.to_dict(orient<span class="op">=</span><span class="st">'records'</span>)).getMarkdown())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>```
+--------------------------------------------------+
| pp1 | pp2 | pp3 |  pair | mean|pop_var|sample_var|
+-----+-----+-----+-------+-----+-------+----------+
|150.0|160.0| nan |1 and 2|155.0| 16.67 |   25.0   |
+-----+-----+-----+-------+-----+-------+----------+
|150.0| nan |170.0|1 and 3|160.0| 66.67 |   100.0  |
+-----+-----+-----+-------+-----+-------+----------+
| nan |160.0|170.0|2 and 3|165.0| 16.67 |   25.0   |
+--------------------------------------------------+```</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mean_sample_mean <span class="op">=</span> sample_heights[<span class="st">'mean'</span>].mean()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>mean_sample_variance <span class="op">=</span> sample_heights[<span class="st">'sample_var'</span>].mean()</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>mean_population_variance <span class="op">=</span> sample_heights[<span class="st">'pop_var'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>When comparing the population mean to the mean sample mean (i.e., what is the typical mean for any sample), they’re identical (i.e.&nbsp;<strong><em>NOT</em></strong> biased):</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>population_height_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 160</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mean_sample_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 160</code></pre>
</div>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>population_height_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    160.0
dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mean_sample_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>160.0</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Whereas when comparing the actual population variance (<strong>population_height_variance</strong>) to the mean (to identify what is a typical) estimate of variance using the <strong>population formula that should not be used for samples (mean_population_variance)</strong> finds the estimate of variance is typically smaller than the actual variance in the population:</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>population_height_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.66667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>mean_population_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.33333</code></pre>
</div>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>population_height_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    66.666667
dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mean_population_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>33.333333333333336</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>As this bias (almost) always underestimates the population variance, <strong>degrees of freedom</strong> is a useful correction to address this within calculations of sample variance. Lets compare the <strong>actual</strong> population height variance (population_height_variance) to the mean estimate using degrees of freedom that <strong>should be used for samples (mean_sample_variance)</strong>.</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>population_height_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.66667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>mean_sample_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50</code></pre>
</div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>population_height_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    66.666667
dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>mean_sample_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>50.0</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>So, not perfect, but this is less under-representative of the variance.</p>
<p>One thing to bear in mind is that calculation of some statistics does <strong>not</strong> require use of the degrees of freedom to correct for <em>bias</em> (as seen above, <strong>mean</strong> was not susceptible to bias).</p>
<p>If you would like to understand how degrees of freedom are determined, and what the thinking is behind this term, read on for a brief description of this (otherwise, feel free to skip to the next section).</p>
<p><strong>Degrees of freedom</strong> refers to how many values could change in your variable once you know what the outcome of the relevant statistic is. For example, if you’re interested in the variance of the height of the three people, then you only have 2 degrees of freedom, because once you know the height of 2 of the participants <strong>AND</strong> the variance of the height, then there the remaining participant only has a 2 possible heights (so their height isn’t <strong>free</strong> to change).</p>
</section>
<section id="standard-deviation-sd" class="level2">
<h2 class="anchored" data-anchor-id="standard-deviation-sd">Standard deviation (SD)</h2>
<p><strong>Standard deviation</strong> is the <strong>square root</strong> of the variance. This takes into account that that the variance includes the <strong>square</strong> of the difference between the individual values and the mean:</p>
<p><strong>Population Variance</strong> <span class="math display">\[
\sigma^2 = \frac{\sum((x_i- \bar{x}{})\color{Red}{^2}\color{Black})} {N}
\]</span></p>
<p><strong>Population SD</strong> <span class="math display">\[
\sigma = \sqrt\frac{\sum((x_i- \bar{x}{})\color{Red}{^2}\color{Black})} {N}
\]</span></p>
<p><strong>Sample Variance</strong> <span class="math display">\[
S^2 = \frac{\sum((x_i- \bar{x}{} )\color{red}{^2}\color{Black})} {N - 1}
\]</span> <strong>Sample SD</strong> <span class="math display">\[
S = \sqrt\frac{\sum((x_i- \bar{x}{} )\color{red}{^2}\color{Black})} {N - 1}
\]</span></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>